shfmt

diff --git a/bin/git b/bin/git
--- a/bin/git
+++ b/bin/git
@@ -8,7 +8,6 @@
 # Short-cutted, for speed:
 THIS_SCRIPT="Jake's ~/bin/git"
 
-
 # TODO: a mechanism by which I can 'lock' this script to unix-land or windows-land
 # TODO: respect --git-dir, --work-tree, and -C, which take precedence over either GIT_DIR or PWD.
 # (See the git man entry for -C, and https://stackoverflow.com/a/35899275 for details)
@@ -32,8 +31,8 @@ WHICH=WSL
 # condenses $HOME to ~, per https://superuser.com/questions/512061/how-to-get-foo-from-home-user1-foo/512078#512078
 # plus vcsh, plus any others that might be relevant in the future
 function summarize_path {
-  local first="${1/#$VCSH_REPO_D\//\$VCSH_REPO_D/}"
-  echo "${first/~/\~}"
+	local first="${1/#$VCSH_REPO_D\//\$VCSH_REPO_D/}"
+	echo "${first/~/\~}"
 }
 
 # Improve ^C behavior - print out this diagnostic/status message even if the user cancels the command
@@ -44,65 +43,62 @@ function summarize_path {
 # Further consideration could go into a magic parameter setup (git -c jake.custom.indirection.disableMessage) that
 # can act as a "quiet, but for this callout only"
 # Further TODO: call out what command was eventually invoked, with env variables, if some debug indications are present
-if [ -t 1 ] && [ -z "$MR_REPO" ] && [ -z "$JAKE_SUPPRESS_GIT_SQUAWK" ] ; then # we're running in a terminal, and not from `mr`
-  trap 'echo "(${THIS_SCRIPT} used ${WHICH}'"'"'s ${GIT}${HOW})"' EXIT
+if [ -t 1 ] && [ -z "$MR_REPO" ] && [ -z "$JAKE_SUPPRESS_GIT_SQUAWK" ]; then # we're running in a terminal, and not from `mr`
+	trap 'echo "(${THIS_SCRIPT} used ${WHICH}'"'"'s ${GIT}${HOW})"' EXIT
 fi
 
 # TODO: I'd like to add implicitdiff to the list of commands which use /usr/bin/git, but respect windows dirs
 # This ad-hoc jumble isn't really condusive to adding more pieces. Perhaps a series of flags (which could be received from
 # the parent environment) could help make the fallback choices clearer.
-if [ "$#" -eq 0 ] ; then
-  : # do nothing - keep $GIT at linux
-elif [ "$1" == "symbolic-ref" ] || [ "$1" == "help" ] ; then
-  : # do nothing - WSL reads symbolic refs faster than windows
-  # We could eventually add this, but it feels unnecessary right now:
-  # GIT_CONFIG_SYSTEM='/mnt/c/Program Files/Git/etc/gitconfig'
+if [ "$#" -eq 0 ]; then
+	: # do nothing - keep $GIT at linux
+elif [ "$1" == "symbolic-ref" ] || [ "$1" == "help" ]; then
+	: # do nothing - WSL reads symbolic refs faster than windows
+	# We could eventually add this, but it feels unnecessary right now:
+	# GIT_CONFIG_SYSTEM='/mnt/c/Program Files/Git/etc/gitconfig'
 else
-  case "$(realpath "$WHERE")" in
-    /mnt/c/*)
-      if  [ "$1" == "config" ] ; then
-        # WSL's git is faster for this, but we need to know to read
-        # Window's config file roots
-        HOW=", reading Window's GIT_CONFIG_* variables"
-        export GIT_CONFIG_SYSTEM='/mnt/c/Program Files/Git/etc/gitconfig'
-        # :? fails if the variable is unset, with a reasonable error
-        # TODO: WSL probably reserves global variables here. Probably pick a new name :\
-        export GIT_CONFIG_GLOBAL="${WSL_WINDOWS_USER_HOME:?}/.gitconfig"
-      else
-        WHICH=Windows
-        GIT=git.exe
-      fi
-      ;;
-   *)
-  esac
+	case "$(realpath "$WHERE")" in
+		/mnt/c/*)
+			if [ "$1" == "config" ]; then
+				# WSL's git is faster for this, but we need to know to read
+				# Window's config file roots
+				HOW=", reading Window's GIT_CONFIG_* variables"
+				export GIT_CONFIG_SYSTEM='/mnt/c/Program Files/Git/etc/gitconfig'
+				# :? fails if the variable is unset, with a reasonable error
+				# TODO: WSL probably reserves global variables here. Probably pick a new name :\
+				export GIT_CONFIG_GLOBAL="${WSL_WINDOWS_USER_HOME:?}/.gitconfig"
+			else
+				WHICH=Windows
+				GIT=git.exe
+			fi
+			;;
+		*) ;;
+	esac
 fi
 
 # Fallback to check my `config` dotfiles repo, but only when I'm not thinking super hard about it
 # (let an explicit choice override my implicit choice)
-if [ -n "$GIT_DIR" ] ; then
-  HOW="${HOW}. Received GIT_DIR=\"$(summarize_path "$GIT_DIR")\""
-elif [ "$WHICH" == WSL ] && [ -z "$HOW" ] && [ "$1" != clone ] && [ "$1" != init ] && ! "$GIT" rev-parse &>/dev/null ; then
-  # Only check for this if we're in WSL-land, because it's slow to check with Window's git.exe
-  # ... not even if we're using WSL-git for faster config reading
-  # ...    nor   if we'd overwrite a different GIT_DIR
-  # ... and FOR SURE not if we're trying to clone or init!
-  # Finally, a fast-failing git command (rev-parse works) tells us that we're outside any other repo
+if [ -n "$GIT_DIR" ]; then
+	HOW="${HOW}. Received GIT_DIR=\"$(summarize_path "$GIT_DIR")\""
+elif [ "$WHICH" == WSL ] && [ -z "$HOW" ] && [ "$1" != clone ] && [ "$1" != init ] && ! "$GIT" rev-parse &> /dev/null; then
+	# Only check for this if we're in WSL-land, because it's slow to check with Window's git.exe
+	# ... not even if we're using WSL-git for faster config reading
+	# ...    nor   if we'd overwrite a different GIT_DIR
+	# ... and FOR SURE not if we're trying to clone or init!
+	# Finally, a fast-failing git command (rev-parse works) tells us that we're outside any other repo
 
-  HOW=". Implicit GIT_DIR=\"$(summarize_path "$BASH_IT_DOTFILES_GIT_REPO")\""
-  # :? fails if the variable is unset, with a reasonable error
-  export GIT_DIR="${BASH_IT_DOTFILES_GIT_REPO:?}"
+	HOW=". Implicit GIT_DIR=\"$(summarize_path "$BASH_IT_DOTFILES_GIT_REPO")\""
+	# :? fails if the variable is unset, with a reasonable error
+	export GIT_DIR="${BASH_IT_DOTFILES_GIT_REPO:?}"
 
-  # TODO: I'd like to export this to pair with GIT_DIR, but the currently-working situation is to set core.worktree on my repo instead
-  # (libgit2, used by git2-rs, and ultimately bat chokes if this variable is set, but respects core.worktree, which I recommend
-  # in the bash-it repo plugin for this setup)
-  # export GIT_WORK_TREE="$HOME"
+	# TODO: I'd like to export this to pair with GIT_DIR, but the currently-working situation is to set core.worktree on my repo instead
+	# (libgit2, used by git2-rs, and ultimately bat chokes if this variable is set, but respects core.worktree, which I recommend
+	# in the bash-it repo plugin for this setup)
+	# export GIT_WORK_TREE="$HOME"
 fi
-
 
 echo "$$ (in $PWD) - git" "$@" >> ~/git-commands
 "$GIT" "$@"
 EXIT_CODE=$?
 echo "$$ exiting with $EXIT_CODE" >> ~/git-commands
 exit $EXIT_CODE
-
-
diff --git a/bin/git-implicitdiff b/bin/git-implicitdiff
--- a/bin/git-implicitdiff
+++ b/bin/git-implicitdiff
@@ -1,40 +1,40 @@
 #!/bin/bash
 
 function help() {
-  echo "usage: git implicitdiff [<no arguments>]"
-  echo
-  echo "Run a git diff, but if there is no difference, give additional information"
-  echo "similar to git status."
+	echo "usage: git implicitdiff [<no arguments>]"
+	echo
+	echo "Run a git diff, but if there is no difference, give additional information"
+	echo "similar to git status."
 }
 
 # hidden feature: --help is a 'valid' option (prevents failure)
-if [ "$1" == '--help' ] ; then
-  help
-  exit
-elif [ $# -gt 0 ] ; then
-  help >&2
-  exit 1
+if [ "$1" == '--help' ]; then
+	help
+	exit
+elif [ $# -gt 0 ]; then
+	help >&2
+	exit 1
 fi
 
 # --quiet and --exit-code disable the pager, so we have to 'peek'
 # also - --quiet doesn't suppress stderr if you're outside a git dir
-git diff --quiet 2>/dev/null
+git diff --quiet 2> /dev/null
 RET=$?
 
-if [ "$RET" -eq 1 ] ; then
-  # legitimate differences - let's do the actual paged output
-  git diff
-elif [ "$RET" -eq 0 ] ; then
-  # "Success" - there is no difference, and we should supplement
-  # the lack-of-output from git diff
-  git status
-elif [ "$RET" -eq 129 ] ; then
-  # "Not in git directory". git status prints a good error message for this case
-  git status
+if [ "$RET" -eq 1 ]; then
+	# legitimate differences - let's do the actual paged output
+	git diff
+elif [ "$RET" -eq 0 ]; then
+	# "Success" - there is no difference, and we should supplement
+	# the lack-of-output from git diff
+	git status
+elif [ "$RET" -eq 129 ]; then
+	# "Not in git directory". git status prints a good error message for this case
+	git status
 else
-  # Failure due to some unknown reason
-  # Hopefully git status fails for a similar reason and
-  # will report what is wrong better than we can
-  echo "${0}: git-diff failed with code ${RET}. Trying git-status:" >&2
-  git status
+	# Failure due to some unknown reason
+	# Hopefully git status fails for a similar reason and
+	# will report what is wrong better than we can
+	echo "${0}: git-diff failed with code ${RET}. Trying git-status:" >&2
+	git status
 fi
