allow fallback to current branch; improve output formatting

diff --git a/.config/git/config b/.config/git/config
--- a/.config/git/config
+++ b/.config/git/config
@@ -145,17 +145,23 @@
 	#  branch for main
 	branch-alias = "!f() { \
 		local newBranch existingBranch; \
-		newBranch=${1?need a name for the new branch}; \
+		newBranch=${1:?need a name for the new branch}; \
 		existingBranch=${2}; \
+		if [ -z \"$existingBranch\" ]; then \
+			if ! existingBranch=\"$(git current-branch 2>/dev/null)\" ; then \
+				>&2 echo not on a current branch. Please specify a branch to alias from; \
+				return 1; \
+			fi \
+		fi; \
 		if ! git commit-ish-exists \"$existingBranch\"; then \
-			echo \"cannot create alias $newBranch for $existingBranch - $existingBranch does not exist \"; \
+			>&2 echo \"cannot create alias $newBranch for $existingBranch - $existingBranch does not exist \"; \
 			return 1; \
 		elif git commit-ish-exists \"$newBranch\"; then \
-			echo \"cannot create alias $newBranch for $existingBranch - $newBranch already exists\"; \
+			>&2 echo \"cannot create alias $newBranch for $existingBranch - $newBranch already exists\"; \
 			return 1; \
 		else \
 			git symbolic-ref refs/heads/main refs/heads/master && \
-			echo \"successfully aliased  $newBranch for $existingBranch\"; \
+			echo \"successfully aliased $newBranch for $existingBranch\"; \
 		fi \
 		} ; f"
 	branch-alias-main-for-master = branch-alias main master
@@ -192,6 +198,9 @@
 
 	# TODO: if stdout is tty, print "$1 exists" or "$1 doesn't exist in git as a commitish object"
 	commit-ish-exists = "!f() { git rev-parse --verify --end-of-options ${1?}^{commit} >/dev/null 2>&1 ; } ; f"
+	# ref: https://stackoverflow.com/questions/6245570/how-do-i-get-the-current-branch-name-in-git
+	# NB: git branch --show-current is less good - succeeds with empty string in detached head state
+	current-branch = "!f() { git symbolic-ref --short HEAD ; } ; f"
 	# Read this as "run git in a delta-like mode for this current interaction"
 	# And don't confuse it with my bash alias for delta, which uses *this* to invoke git-implicitdiff
 	# NB: the [delta] sections below configures the particular --features I'm using here
