a suite of "what git commands are available" commands, which need pruning

diff --git a/.config/git/config b/.config/git/config
--- a/.config/git/config
+++ b/.config/git/config
@@ -28,6 +28,9 @@
 	    -"git--list-cmds=list-foreignscminterface(the-broken-ones-at-least)" \
 	    -archimport -cvsexportcommit -cvsimport -cvsserver -p4 -send-email -svn \
 		"
+	# NB: these are not used by git but instead by my custom command checking aliases below
+	categories = list-ancillaryinterrogators,list-ancillarymanipulators,list-complete,list-developerinterfaces,list-foreignscminterface,list-guide,list-mainporcelain,list-plumbinginterrogators,list-plumbingmanipulators,list-purehelpers,list-synchelpers,list-synchingrepositories,list-userinterfaces
+	failing-commands =
 [alias]
 	# TODO: if any of these categories become onery, I can just break them out into include sections
 	# Typos (alphabetical by correct name) ("I mashed my keyboard and expected this to work")
@@ -275,7 +278,43 @@
 	# This seems to be because those commands live as dependencies of apt's git-all
 	# TODO: `git is-valid-git-command --help` incorrectly reports that --help is a git command, and coincidentally prints this alias. (thanks git-help!)
 	# But `git is-valid-git-command -- --help` fails, because `--` is not a command.
-	list-valid-git-commands = !git --list-cmds=list-mainporcelain,others,nohelpers,alias,list-complete,config
+	# list of all list-Xs was originally generated by my own bash pipeline, but I wrote this alias to automate it
+	# curl https://raw.githubusercontent.com/git/git/master/command-list.txt | awk '!/^#/{print $2}' | sort | uniq | awk '{if(a)a=a ","; a=a "list-" $0} END {print a}'
+	update-completion-categories-list = "!f() { \n\
+			git config set --global completion.categories \"$( \n\
+				curl https://raw.githubusercontent.com/git/git/master/command-list.txt | \n\
+					awk '!/^#/{print $2}' | \n\
+					sort | \n\
+					uniq | \n\
+					awk '{ \n\
+						if(a) { \n\
+							a = a \",\"; \n\
+						} \n\
+						a = a \"list-\" $0; \n\
+					} \n\
+					END { \n\
+						print a \n\
+					}' \n\
+			)\" \n\
+		} ; f"
+	list-all-valid-git-commands = "!f() { git --list-cmds=$(git config get completion.categories),others,nohelpers,alias | sort | uniq ; } ; f"
+	list-reasonable-git-commands = !git --list-cmds=list-mainporcelain,others,nohelpers,alias,list-complete,config
+	# NB: a digression from !f() - I need bash's process substitution for this to be at all short
+	list-unreasonable-git-commands = "!bash -c 'f() { \n\
+			comm -23 <(git list-all-valid-git-commands | sort | uniq) <(git list-reasonable-git-commands | sort | uniq) ; \n\
+		} ; f'"
+
+	list-failing-git-commands = "!f() { \n\
+			local i; \n\
+			# NB: word splitting and the rules for git commands mean I don't fear not-quoting $i here \n\
+			for i in $(git list-all-valid-git-commands); do \n\
+				if ! (git help $i || git $i help) >/dev/null 2>&1; then \n\
+					echo $i # failed! \n\
+				fi \n\
+			done \n\
+		} ; f"
+
+
 	is-valid-git-command = "!f() { git list-valid-git-commands | grep -q -s --line-regexp --fixed-strings \"${1?Need a value}\" ; } ; f"
 	# --local is unnecessary, but provides clarity
 	silence-mr-pull =  "!f() { git config set --local merge.stat no ; } ; f"
