refactor: include newlines in !f() values

diff --git a/.config/git/config b/.config/git/config
--- a/.config/git/config
+++ b/.config/git/config
@@ -54,13 +54,13 @@
 	autostash = pull --rebase --autostash # My brain also expects an implicit rebase when I'm talking about autostash
 	bare = clone --bare
 	branches = branch -a # Originally a typo from bash-land, I realized this could be an even better command
-	bp = "!f() { \
-		: big-picture; \
-		if test \"$#\" -eq 0; then \
-			git big-picture -v x-www-browser; \
-		else \
-			git big-picture \"$@\"; \
-		fi \
+	bp = "!f() { \n\
+		: big-picture; \n\
+		if test \"$#\" -eq 0; then \n\
+			git big-picture -v x-www-browser; \n\
+		else \n\
+			git big-picture \"$@\"; \n\
+		fi \n\
 		} ; f"
 	co = checkout
 	config-editg = config -e --global
@@ -75,13 +75,13 @@
 	no-columns = -c column.ui=never -c column.branch=never -c column.clean=never -c column.status=never -c column.tag=never # disable columning in a further git command
 
 	# borrowed from my bash-implicit-git function `remote`, which we can't offer here, but its `remotes` alias can be duplicated here
-	remotes = "!f() { \
-		: remote; \
-		if test \"$#\" -eq 0 || test show = \"$1\"; then \
-			git remote -v \"$@\"; \
-		else \
-			git remote \"$@\" ; \
-		fi \
+	remotes = "!f() { \n\
+		: remote; \n\
+		if test \"$#\" -eq 0 || test show = \"$1\"; then \n\
+			git remote -v \"$@\"; \n\
+		else \n\
+			git remote \"$@\" ; \n\
+		fi \n\
 		} ; f"
 	submodules = submodule # arguably a typo, but I thought this was a proper command name
 
@@ -143,33 +143,33 @@
 	# TODO: this is from https://stackoverflow.com/questions/14365946/create-a-branch-alias
 	#  and I'm not certain if it has any nasty consequences if I later want to create a proper
 	#  branch for main
-	branch-alias = "!f() { \
-		local newBranch existingBranch; \
-		newBranch=${1:?need a name for the new branch}; \
-		existingBranch=${2}; \
-		if [ -z \"$existingBranch\" ]; then \
-			if ! existingBranch=\"$(git current-branch 2>/dev/null)\" ; then \
-				>&2 echo not on a current branch. Please specify a branch to alias from; \
-				return 1; \
-			fi \
-		fi; \
-		if ! git commit-ish-exists \"$existingBranch\"; then \
-			>&2 echo \"cannot create alias $newBranch for $existingBranch - $existingBranch does not exist \"; \
-			return 1; \
-		elif git commit-ish-exists \"$newBranch\"; then \
-			>&2 echo \"cannot create alias $newBranch for $existingBranch - $newBranch already exists\"; \
-			return 1; \
-		else \
-			git symbolic-ref refs/heads/main refs/heads/master && \
-			echo \"successfully aliased $newBranch for $existingBranch\"; \
-		fi \
+	branch-alias = "!f() { \n\
+		local newBranch existingBranch; \n\
+		newBranch=${1:?need a name for the new branch}; \n\
+		existingBranch=${2}; \n\
+		if [ -z \"$existingBranch\" ]; then \n\
+			if ! existingBranch=\"$(git current-branch 2>/dev/null)\" ; then \n\
+				>&2 echo not on a current branch. Please specify a branch to alias from; \n\
+				return 1; \n\
+			fi \n\
+		fi; \n\
+		if ! git commit-ish-exists \"$existingBranch\"; then \n\
+			>&2 echo \"cannot create alias $newBranch for $existingBranch - $existingBranch does not exist \"; \n\
+			return 1; \n\
+		elif git commit-ish-exists \"$newBranch\"; then \n\
+			>&2 echo \"cannot create alias $newBranch for $existingBranch - $newBranch already exists\"; \n\
+			return 1; \n\
+		else \n\
+			git symbolic-ref refs/heads/main refs/heads/master && \n\
+			echo \"successfully aliased $newBranch for $existingBranch\"; \n\
+		fi \n\
 		} ; f"
 	branch-alias-main-for-master = branch-alias main master
 
-	arguments-debug = "!f(){ \
-		for i; do \
-			echo \"'$i'\"; \
-		done ; \
+	arguments-debug = "!f(){ \n\
+		for i; do \n\
+			echo \"'$i'\"; \n\
+		done ; \n\
 		} ; f"
 	# https://stackoverflow.com/questions/2363197/can-i-get-a-list-of-files-marked-assume-unchanged/2363495#2363495
 	# (leveraging the function tech defined below)
@@ -229,10 +229,10 @@
 	# Stolen from mr's git_status action
 	# TODO: --simplify-by-decoration is a good "trim the tree to relevant bits" flag. Potentially use it in more places
 	# TODO: I'd also like the upstream mr-status to list commits from local branches that aren't pushed to their tracked branches
-	mr-status = "!f() { \
-			git status -s \"$@\"; \
-			git --no-pager log --branches --not --remotes --simplify-by-decoration --decorate --oneline; \
-			git --no-pager stash list; \
+	mr-status = "!f() { \n\
+			git status -s \"$@\"; \n\
+			git --no-pager log --branches --not --remotes --simplify-by-decoration --decorate --oneline; \n\
+			git --no-pager stash list; \n\
 		} ; f"
 
 	# TODO: also need to expire the reflog with  git reflog expire --expire=all --all, per https://stackoverflow.com/a/62650346/285944
@@ -240,12 +240,12 @@
 	# In fact, it might be nice to 'stash' two files - one for the tags and one for the reflog so they can be restored
 	# Alternatively, following github's "Here are your local changes. Please type the name of this repo to proceed" prompt might be cool, too
 	# I should also do something along the lines of "create a shallow (--depth=1) clone; compare its .git dir's size"
-	reshallow = "!f() { \
-			echo 'deleting tags:'; \
-			git show-ref --tags; \
-			git tag -d $(git tag -l); \
-			git pull --rebase --no-tags --depth 1; \
-			git gc --prune=all; \
+	reshallow = "!f() { \n\
+			echo 'deleting tags:'; \n\
+			git show-ref --tags; \n\
+			git tag -d $(git tag -l); \n\
+			git pull --rebase --no-tags --depth 1; \n\
+			git gc --prune=all; \n\
 		} ; f"
 [fetch]
 	all = true   # Fetch should assume --all. Thank you git 2.44 :D
